export const PRODUCT_ACTIONS = {
    SET_LOADING: "@PRODUCT_ACTIONS/SET_LOADING",
    GET_PRODUCTS: "@PRODUCT_ACTIONS/GET_PRODUCTS",
    GET_PRODUCTS_REQUEST: "@PRODUCT_ACTIONS/GET_PRODUCTS_REQUEST",
    CREATE_PRODUCT: "@PRODUCT_ACTIONS/CREATE_PRODUCT",
    CREATE_PRODUCT_REQUEST: "@PRODUCT_ACTIONS/CREATE_PRODUCT_REQUEST",
    UPDATE_PRODUCT: "@PRODUCT_ACTIONS/UPDATE_PRODUCT",
    UPDATE_PRODUCT_REQUEST: "@PRODUCT_ACTIONS/UPDATE_PRODUCT_REQUEST",
    DELETE_PRODUCT: "@PRODUCT_ACTIONS/DELETE_PRODUCT",
    DELETE_PRODUCT_REQUEST: "@PRODUCT_ACTIONS/DELETE_PRODUCT_REQUEST",
}