export const PRODUCT_ACTIONS = {
    SET_LOADING: "SET_LOADING",
    GET_PRODUCTS: "GET_PRODUCTS",
    GET_PRODUCTS_REQUEST: "GET_PRODUCTS_REQUEST",
    CREATE_PRODUCT: "CREATE_PRODUCT",
    CREATE_PRODUCT_REQUEST: "CREATE_PRODUCT_REQUEST",
    UPDATE_PRODUCT: "UPDATE_PRODUCT",
    UPDATE_PRODUCT_REQUEST: "UPDATE_PRODUCT_REQUEST",
    DELETE_PRODUCT: "DELETE_PRODUCT",
    DELETE_PRODUCT_REQUEST: "DELETE_PRODUCT_REQUEST",
}